name: Realeses Test and Push

on:
  release:
    types: [created]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:  
      -
        name: Checkout
        uses: actions/checkout@v4

      -
        name: Use Node.js 
        uses: actions/setup-node@v4
        with:
          node-version: 22

      # - 
      #   name: Install Dependencies
      #   run: npm ci
        
      # - 
      #   name: Run Tests
      #   run: npm test  

      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{secrets.DOCKERHUB_USERNAME}}/jaya-devicenet-v2
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern=latest
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
